feat: Mark a consumer or stream has not deletable
nats-io/nack pull request #89
Opened 2022-10-26 15:47 UTC by danielcibrao-form3

The following PR aims to ensure that resources managed by NACK should not be deleted by him on any ocassion that a CRD disappears. This is specially painfully on a multi cloud setup were nack is deployed into several clouds and by delete a CRD on accident on a cloud it delete that resouce for all other clouds which should not be the case.

2022-10-26 17:47 UTC, caleblloyd commented
Managed Resource Deletion has historically been handled in Finalizers in Operators, but in NACK is being handled in a list/clean loop that was implemented in #56 

I have opened #90 to try to figure out if we should go back to a Finalizer approach for resource deletion

If we used finalizers, then only a Deleted CRD Finalizer would be able to delete a Managed NATS Stream or Consumer, so you wouldn't get any ghost deletes from a missing CRD

2022-10-26 19:19 UTC, caleblloyd requested changes
Wording in the descriptions is backwards, I've suggested some wording that should be a little clearer

2022-10-26 19:19 UTC, caleblloyd commented on deploy/crds.yml
> +                description: Indicates if a Stream can be deleted (true) or not (false)
This should say `When true, the managed Stream will not be deleted when the resource is deleted`

2022-10-26 19:19 UTC, caleblloyd commented on deploy/crds.yml
> +                description: Indicates if a Consumer can be deleted (true) or not (false)
This should say `When true, the managed Consumer will not be deleted when the resource is deleted`

2022-10-27 13:40 UTC, caleblloyd reviewed
I updated the descriptions, I think this looks good now.  Would like to get @wallyqs opinion on it too though

2022-10-27 13:40 UTC, caleblloyd commented on deploy/crds.yml
> +                description: Indicates if a Consumer can be deleted (true) or not (false)
I made this change to the description

2022-10-27 13:40 UTC, caleblloyd commented on deploy/crds.yml
> +                description: Indicates if a Stream can be deleted (true) or not (false)
I made this change to the description

2022-10-31 19:00 UTC, wallyqs approved these changes
LGTM

2022-11-17 21:58 UTC, caleblloyd approved these changes

2022-11-17 21:58 UTC, merged